根据默认音频输入流的音量来决定口型大小的功能
yuyuyzl/EasyVtuber pull request #8
Opened 2023-01-14 03:27 UTC by PipeYume

用于有提前配音的录制感觉比较方便。

注：该功能在main.py中写在后面的，所以会覆盖 面捕的口型大小。

在 args.py 中添加 args.auto_mouth_threshold 参数，该参数用于归一化音量。当该参数为0时，表示不使用这个功能。个人测试感觉 8000 比较好。

在 launcher.py 中 增加了获取用户输入的UI。

在 main.py中 使用pyaudio 来获取音频输入流并改变口型大小。

额外：我的环境中OpenSeeFace的面捕的口型较小，眼睛闭不了，所以增加了对于 口型和眼睛 开合 的调整函数。

2023-01-30 09:51 UTC, yuyuyzl reviewed
感谢PR
如果确实需要加这个功能会参考的
眼睛嘴巴识别的话 OSF输入还是以调整摄像头位置为主
最好是通过OSF输出的点集手动匹配 这样能出不同口型 我直接用自带的数据还是有点偷懒了

2023-04-24 13:09 UTC, LittleZzUni commented
我想问下为什么 iFacialMocap连上后 会显示timeout

2023-05-09 23:27 UTC, harukaxxxx requested changes
also need to add `pyaudio` in `requirements.txt`

2023-05-09 23:27 UTC, harukaxxxx commented on main.py
> +                                channels=2,
`channels=p.get_default_input_device_info()["maxInputChannels"]`

2023-05-09 23:27 UTC, harukaxxxx commented on main.py
> +                                rate=44100,
`rate=int(p.get_default_input_device_info()["defaultSampleRate"])`

2025-02-20 03:38 UTC, closed without merging